cc_binary(
  name = "list",
  srcs = ["test_list.cc"],
  deps = ["//src:printer", "//src:list"]
)
cc_binary(
  name = "tree",
  srcs = ["test_tree.cc"],
  deps = ["//src:printer", "//src:rbtree", "//src:list"]
)
cc_binary(
  name = "sort",
  srcs = ["test_sort.cc"],
  deps = ["//src:printer", "//src:list", "//src:algorithm"]
)
cc_binary(
  name = "functor",
  srcs = ["test_functor.cc"],
  deps = ["//src:printer", "//src:function_operator", "//src:algorithm"]
)
cc_binary(
  name = "rbtree",
  srcs = ["test_rbtree.cc"],
  deps = ["//src:printer", "//src:rbtree", "//src:list", "//src:algorithm"]
)
